import { priceData } from "../Price/priceData";
export interface SalesProp {
  id: number;
  customerName: string;
  customerType: string;
  address: string;
  date: Date;
  numOfCrate: number;
  price: number;
  amountPaid: number;
}
export const salesData: SalesProp[] = [
  {
    id: 1,
    customerName: "Samuel John",
    customerType: "Wholesaler",
    address: "Durumi",
    date: new Date("2024-03-14"),
    numOfCrate: 100,
    price: priceData[priceData.length - 1].wholeSalersPriceOne,
    amountPaid: 300000,
  },
  {
    id: 2,
    customerName: "Amanda Mba",
    customerType: "Wholesaler",
    address: "Amadi",
    date: new Date("2024-03-15"),
    numOfCrate: 100,
    price: priceData[priceData.length - 1].wholeSalersPriceTwo,
    amountPaid: 340000,
  },
  {
    id: 3,
    customerName: "Lolia Daniei",
    customerType: "Wholesaler",
    address: "Rumuola",
    date: new Date("2024-03-16"),
    numOfCrate: 100,
    price: priceData[priceData.length - 1].wholeSalersPriceOne,
    amountPaid: 0,
  },
  {
    id: 4,
    customerName: "Faith James",
    customerType: "Wholesaler",
    address: "Rumuigbo",
    date: new Date("2024-05-17"),
    numOfCrate: 100,
    price: priceData[priceData.length - 1].wholeSalersPriceTwo,
    amountPaid: 355000,
  },
  {
    id: 5,
    customerName: "Esther Charity",
    customerType: "Retailsaler",
    address: "Abakpa",
    date: new Date("2024-03-18"),
    numOfCrate: 100,
    price: priceData[priceData.length - 1].retailSalersPrice,
    amountPaid: 300000,
  },
  {
    id: 6,
    customerName: "Samuel John",
    customerType: "Wholesaler",
    address: "Durumi",
    date: new Date("2024-03-19"),
    numOfCrate: 100,
    price: priceData[priceData.length - 1].wholeSalersPriceOne,
    amountPaid: 300000,
  },
  {
    id: 7,
    customerName: "Amanda Mba",
    customerType: "Wholesaler",
    address: "Amadi",
    date: new Date("2024-03-20"),
    numOfCrate: 100,
    price: priceData[priceData.length - 1].wholeSalersPriceTwo,
    amountPaid: 300000,
  },
  {
    id: 8,
    customerName: "Lolia Daniei",
    customerType: "Wholesaler",
    address: "Rumuola",
    date: new Date("2024-03-21"),
    numOfCrate: 100,
    price: priceData[priceData.length - 1].wholeSalersPriceOne,
    amountPaid: 300000,
  },
  {
    id: 9,
    customerName: "Faith James",
    customerType: "Wholesaler",
    address: "Rumuigbo",
    date: new Date("2024-05-22"),
    numOfCrate: 100,
    price: priceData[priceData.length - 1].wholeSalersPriceTwo,
    amountPaid: 300000,
  },
  {
    id: 10,
    customerName: "Esther Charity",
    customerType: "Retailsaler",
    address: "Abakpa",
    date: new Date("2024-03-23"),
    numOfCrate: 100,
    price: priceData[priceData.length - 1].retailSalersPrice,
    amountPaid: 300000,
  },
  {
    id: 11,
    customerName: "Samuel John",
    customerType: "Wholesaler",
    address: "Durumi",
    date: new Date("2024-03-24"),
    numOfCrate: 100,
    price: priceData[priceData.length - 1].wholeSalersPriceOne,
    amountPaid: 300000,
  },
  {
    id: 12,
    customerName: "Amanda Mba",
    customerType: "Wholesaler",
    address: "Amadi",
    date: new Date("2024-03-25"),
    numOfCrate: 100,
    price: priceData[priceData.length - 1].wholeSalersPriceTwo,
    amountPaid: 300000,
  },
  {
    id: 13,
    customerName: "Lolia Daniei",
    customerType: "Wholesaler",
    address: "Rumuola",
    date: new Date("2024-03-26"),
    numOfCrate: 100,
    price: priceData[priceData.length - 1].wholeSalersPriceOne,
    amountPaid: 300000,
  },
  {
    id: 14,
    customerName: "Faith James",
    customerType: "Wholesaler",
    address: "Rumuigbo",
    date: new Date("2024-05-27"),
    numOfCrate: 100,
    price: priceData[priceData.length - 1].wholeSalersPriceOne,
    amountPaid: 300000,
  },
  {
    id: 15,
    customerName: "Esther Charity",
    customerType: "Retailsaler",
    address: "Abakpa",
    date: new Date("2024-03-28"),
    numOfCrate: 100,
    price: priceData[priceData.length - 1].retailSalersPrice,
    amountPaid: 300000,
  },
];
